# Use an official Python runtime as a parent image
FROM python:3.9-alpine
# Set the working directory to /app
WORKDIR /usr/src/app
# Copy the requirements file into the container
COPY requirements.txt .
# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt
# Copy the project code into the container
COPY . /usr/src/app
# Expose port 8000 for the Django development server
EXPOSE 8000
# Start the Django development server
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]