# Generated by Django 4.0.4 on 2023-04-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometricDbId', models.IntegerField()),
                ('staffCode', models.CharField(max_length=20)),
                ('attendanceState', models.CharField(max_length=20)),
                ('attendanceDate', models.DateField()),
                ('attendanceTime', models.TimeField()),
                ('deviceSerialNumber', models.CharField(max_length=20)),
                ('branchCode', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staffCode', models.CharField(max_length=20)),
                ('employeeName', models.CharField(max_length=100)),
            ],
        ),
    ]
